<?php

namespace Database\Seeders\General;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    public function run(): void
    {
        $countries = DB::table('countries')->pluck('id', 'code');

        $states = [

            // 🇨🇺 CUBA
            ['country_id' => $countries['CU'], 'code' => 'HABANA', 'name' => 'La Habana'],
            ['country_id' => $countries['CU'], 'code' => 'ARTEMISA', 'name' => 'Artemisa'],
            ['country_id' => $countries['CU'], 'code' => 'MAYABEQUE', 'name' => 'Mayabeque'],
            ['country_id' => $countries['CU'], 'code' => 'PINAR', 'name' => 'Pinar del Río'],
            ['country_id' => $countries['CU'], 'code' => 'MATANZAS', 'name' => 'Matanzas'],
            ['country_id' => $countries['CU'], 'code' => 'VILLA_CLARA', 'name' => 'Villa Clara'],
            ['country_id' => $countries['CU'], 'code' => 'CIENFUEGOS', 'name' => 'Cienfuegos'],
            ['country_id' => $countries['CU'], 'code' => 'SANCTI', 'name' => 'Sancti Spíritus'],
            ['country_id' => $countries['CU'], 'code' => 'CIEGO', 'name' => 'Ciego de Ávila'],
            ['country_id' => $countries['CU'], 'code' => 'CAMAGUEY', 'name' => 'Camagüey'],
            ['country_id' => $countries['CU'], 'code' => 'LAS_TUNAS', 'name' => 'Las Tunas'],
            ['country_id' => $countries['CU'], 'code' => 'HOLGUIN', 'name' => 'Holguín'],
            ['country_id' => $countries['CU'], 'code' => 'GRANMA', 'name' => 'Granma'],
            ['country_id' => $countries['CU'], 'code' => 'SANTIAGO', 'name' => 'Santiago de Cuba'],
            ['country_id' => $countries['CU'], 'code' => 'GUANTANAMO', 'name' => 'Guantánamo'],
            ['country_id' => $countries['CU'], 'code' => 'ISLA_JUVENTUD', 'name' => 'Isla de la Juventud'],

            // 🇪🇨 ECUADOR
            ['country_id' => $countries['EC'], 'code' => 'AZUAY', 'name' => 'Azuay'],
            ['country_id' => $countries['EC'], 'code' => 'BOLIVAR', 'name' => 'Bolívar'],
            ['country_id' => $countries['EC'], 'code' => 'CANAR', 'name' => 'Cañar'],
            ['country_id' => $countries['EC'], 'code' => 'CARCHI', 'name' => 'Carchi'],
            ['country_id' => $countries['EC'], 'code' => 'CHIMBORAZO', 'name' => 'Chimborazo'],
            ['country_id' => $countries['EC'], 'code' => 'COTOPAXI', 'name' => 'Cotopaxi'],
            ['country_id' => $countries['EC'], 'code' => 'EL_ORO', 'name' => 'El Oro'],
            ['country_id' => $countries['EC'], 'code' => 'ESMERALDAS', 'name' => 'Esmeraldas'],
            ['country_id' => $countries['EC'], 'code' => 'GALAPAGOS', 'name' => 'Galápagos'],
            ['country_id' => $countries['EC'], 'code' => 'GUAYAS', 'name' => 'Guayas'],
            ['country_id' => $countries['EC'], 'code' => 'IMBABURA', 'name' => 'Imbabura'],
            ['country_id' => $countries['EC'], 'code' => 'LOJA', 'name' => 'Loja'],
            ['country_id' => $countries['EC'], 'code' => 'LOS_RIOS', 'name' => 'Los Ríos'],
            ['country_id' => $countries['EC'], 'code' => 'MANABI', 'name' => 'Manabí'],
            ['country_id' => $countries['EC'], 'code' => 'MORONA_SANTIAGO', 'name' => 'Morona Santiago'],
            ['country_id' => $countries['EC'], 'code' => 'NAPO', 'name' => 'Napo'],
            ['country_id' => $countries['EC'], 'code' => 'ORELLANA', 'name' => 'Orellana'],
            ['country_id' => $countries['EC'], 'code' => 'PASTAZA', 'name' => 'Pastaza'],
            ['country_id' => $countries['EC'], 'code' => 'PICHINCHA', 'name' => 'Pichincha'],
            ['country_id' => $countries['EC'], 'code' => 'SANTA_ELENA', 'name' => 'Santa Elena'],
            ['country_id' => $countries['EC'], 'code' => 'SANTO_DOMINGO', 'name' => 'Santo Domingo de los Tsáchilas'],
            ['country_id' => $countries['EC'], 'code' => 'SUCUMBIOS', 'name' => 'Sucumbíos'],
            ['country_id' => $countries['EC'], 'code' => 'TUNGURAHUA', 'name' => 'Tungurahua'],
            ['country_id' => $countries['EC'], 'code' => 'ZAMORA_CHINCHIPE', 'name' => 'Zamora Chinchipe'],

            // 🇨🇴 COLOMBIA
            ['country_id' => $countries['CO'], 'code' => 'AMAZONAS', 'name' => 'Amazonas'],
            ['country_id' => $countries['CO'], 'code' => 'ANTIOQUIA', 'name' => 'Antioquia'],
            ['country_id' => $countries['CO'], 'code' => 'ARAUCA', 'name' => 'Arauca'],
            ['country_id' => $countries['CO'], 'code' => 'ATLANTICO', 'name' => 'Atlántico'],
            ['country_id' => $countries['CO'], 'code' => 'BOLIVAR', 'name' => 'Bolívar'],
            ['country_id' => $countries['CO'], 'code' => 'BOYACA', 'name' => 'Boyacá'],
            ['country_id' => $countries['CO'], 'code' => 'CALDAS', 'name' => 'Caldas'],
            ['country_id' => $countries['CO'], 'code' => 'CAQUETA', 'name' => 'Caquetá'],
            ['country_id' => $countries['CO'], 'code' => 'CASANARE', 'name' => 'Casanare'],
            ['country_id' => $countries['CO'], 'code' => 'CAUCA', 'name' => 'Cauca'],
            ['country_id' => $countries['CO'], 'code' => 'CESAR', 'name' => 'Cesar'],
            ['country_id' => $countries['CO'], 'code' => 'CHOCO', 'name' => 'Chocó'],
            ['country_id' => $countries['CO'], 'code' => 'CORDOBA', 'name' => 'Córdoba'],
            ['country_id' => $countries['CO'], 'code' => 'CUNDINAMARCA', 'name' => 'Cundinamarca'],
            ['country_id' => $countries['CO'], 'code' => 'BOGOTA', 'name' => 'Bogotá D.C.'],
            ['country_id' => $countries['CO'], 'code' => 'GUAINIA', 'name' => 'Guainía'],
            ['country_id' => $countries['CO'], 'code' => 'GUAVIARE', 'name' => 'Guaviare'],
            ['country_id' => $countries['CO'], 'code' => 'HUILA', 'name' => 'Huila'],
            ['country_id' => $countries['CO'], 'code' => 'LA_GUAJIRA', 'name' => 'La Guajira'],
            ['country_id' => $countries['CO'], 'code' => 'MAGDALENA', 'name' => 'Magdalena'],
            ['country_id' => $countries['CO'], 'code' => 'META', 'name' => 'Meta'],
            ['country_id' => $countries['CO'], 'code' => 'NARINO', 'name' => 'Nariño'],
            ['country_id' => $countries['CO'], 'code' => 'NORTE_SANTANDER', 'name' => 'Norte de Santander'],
            ['country_id' => $countries['CO'], 'code' => 'PUTUMAYO', 'name' => 'Putumayo'],
            ['country_id' => $countries['CO'], 'code' => 'QUINDIO', 'name' => 'Quindío'],
            ['country_id' => $countries['CO'], 'code' => 'RISARALDA', 'name' => 'Risaralda'],
            ['country_id' => $countries['CO'], 'code' => 'SAN_ANDRES', 'name' => 'San Andrés y Providencia'],
            ['country_id' => $countries['CO'], 'code' => 'SANTANDER', 'name' => 'Santander'],
            ['country_id' => $countries['CO'], 'code' => 'SUCRE', 'name' => 'Sucre'],
            ['country_id' => $countries['CO'], 'code' => 'TOLIMA', 'name' => 'Tolima'],
            ['country_id' => $countries['CO'], 'code' => 'VALLE', 'name' => 'Valle del Cauca'],
            ['country_id' => $countries['CO'], 'code' => 'VAUPES', 'name' => 'Vaupés'],
            ['country_id' => $countries['CO'], 'code' => 'VICHADA', 'name' => 'Vichada'],

            // 🇲🇽 MÉXICO
            ['country_id' => $countries['MX'], 'code' => 'AGUASCALIENTES', 'name' => 'Aguascalientes'],
            ['country_id' => $countries['MX'], 'code' => 'BAJA_CALIFORNIA', 'name' => 'Baja California'],
            ['country_id' => $countries['MX'], 'code' => 'BAJA_CALIFORNIA_SUR', 'name' => 'Baja California Sur'],
            ['country_id' => $countries['MX'], 'code' => 'CAMPECHE', 'name' => 'Campeche'],
            ['country_id' => $countries['MX'], 'code' => 'CHIAPAS', 'name' => 'Chiapas'],
            ['country_id' => $countries['MX'], 'code' => 'CHIHUAHUA', 'name' => 'Chihuahua'],
            ['country_id' => $countries['MX'], 'code' => 'CIUDAD_DE_MEXICO', 'name' => 'Ciudad de México'],
            ['country_id' => $countries['MX'], 'code' => 'COAHUILA', 'name' => 'Coahuila'],
            ['country_id' => $countries['MX'], 'code' => 'COLIMA', 'name' => 'Colima'],
            ['country_id' => $countries['MX'], 'code' => 'DURANGO', 'name' => 'Durango'],
            ['country_id' => $countries['MX'], 'code' => 'GUANAJUATO', 'name' => 'Guanajuato'],
            ['country_id' => $countries['MX'], 'code' => 'GUERRERO', 'name' => 'Guerrero'],
            ['country_id' => $countries['MX'], 'code' => 'HIDALGO', 'name' => 'Hidalgo'],
            ['country_id' => $countries['MX'], 'code' => 'JALISCO', 'name' => 'Jalisco'],
            ['country_id' => $countries['MX'], 'code' => 'ESTADO_DE_MEXICO', 'name' => 'Estado de México'],
            ['country_id' => $countries['MX'], 'code' => 'MICHOACAN', 'name' => 'Michoacán'],
            ['country_id' => $countries['MX'], 'code' => 'MORELOS', 'name' => 'Morelos'],
            ['country_id' => $countries['MX'], 'code' => 'NAYARIT', 'name' => 'Nayarit'],
            ['country_id' => $countries['MX'], 'code' => 'NUEVO_LEON', 'name' => 'Nuevo León'],
            ['country_id' => $countries['MX'], 'code' => 'OAXACA', 'name' => 'Oaxaca'],
            ['country_id' => $countries['MX'], 'code' => 'PUEBLA', 'name' => 'Puebla'],
            ['country_id' => $countries['MX'], 'code' => 'QUERETARO', 'name' => 'Querétaro'],
            ['country_id' => $countries['MX'], 'code' => 'QUINTANA_ROO', 'name' => 'Quintana Roo'],
            ['country_id' => $countries['MX'], 'code' => 'SAN_LUIS_POTOSI', 'name' => 'San Luis Potosí'],
            ['country_id' => $countries['MX'], 'code' => 'SINALOA', 'name' => 'Sinaloa'],
            ['country_id' => $countries['MX'], 'code' => 'SONORA', 'name' => 'Sonora'],
            ['country_id' => $countries['MX'], 'code' => 'TABASCO', 'name' => 'Tabasco'],
            ['country_id' => $countries['MX'], 'code' => 'TAMAULIPAS', 'name' => 'Tamaulipas'],
            ['country_id' => $countries['MX'], 'code' => 'TLAXCALA', 'name' => 'Tlaxcala'],
            ['country_id' => $countries['MX'], 'code' => 'VERACRUZ', 'name' => 'Veracruz'],
            ['country_id' => $countries['MX'], 'code' => 'YUCATAN', 'name' => 'Yucatán'],
            ['country_id' => $countries['MX'], 'code' => 'ZACATECAS', 'name' => 'Zacatecas'],

            // 🇻🇪 VENEZUELA
            ['country_id' => $countries['VE'], 'code' => 'AMAZONAS', 'name' => 'Amazonas'],
            ['country_id' => $countries['VE'], 'code' => 'ANZOATEGUI', 'name' => 'Anzoátegui'],
            ['country_id' => $countries['VE'], 'code' => 'APURE', 'name' => 'Apure'],
            ['country_id' => $countries['VE'], 'code' => 'ARAGUA', 'name' => 'Aragua'],
            ['country_id' => $countries['VE'], 'code' => 'BARINAS', 'name' => 'Barinas'],
            ['country_id' => $countries['VE'], 'code' => 'BOLIVAR', 'name' => 'Bolívar'],
            ['country_id' => $countries['VE'], 'code' => 'CARABOBO', 'name' => 'Carabobo'],
            ['country_id' => $countries['VE'], 'code' => 'COJEDES', 'name' => 'Cojedes'],
            ['country_id' => $countries['VE'], 'code' => 'DELTA_AMACURO', 'name' => 'Delta Amacuro'],
            ['country_id' => $countries['VE'], 'code' => 'FALCON', 'name' => 'Falcón'],
            ['country_id' => $countries['VE'], 'code' => 'GUARICO', 'name' => 'Guárico'],
            ['country_id' => $countries['VE'], 'code' => 'LARA', 'name' => 'Lara'],
            ['country_id' => $countries['VE'], 'code' => 'MERIDA', 'name' => 'Mérida'],
            ['country_id' => $countries['VE'], 'code' => 'MIRANDA', 'name' => 'Miranda'],
            ['country_id' => $countries['VE'], 'code' => 'MONAGAS', 'name' => 'Monagas'],
            ['country_id' => $countries['VE'], 'code' => 'NUEVA_ESPARTA', 'name' => 'Nueva Esparta'],
            ['country_id' => $countries['VE'], 'code' => 'PORTUGUESA', 'name' => 'Portuguesa'],
            ['country_id' => $countries['VE'], 'code' => 'SUCRE', 'name' => 'Sucre'],
            ['country_id' => $countries['VE'], 'code' => 'TACHIRA', 'name' => 'Táchira'],
            ['country_id' => $countries['VE'], 'code' => 'TRUJILLO', 'name' => 'Trujillo'],
            ['country_id' => $countries['VE'], 'code' => 'VARGAS', 'name' => 'La Guaira'],
            ['country_id' => $countries['VE'], 'code' => 'YARACUY', 'name' => 'Yaracuy'],
            ['country_id' => $countries['VE'], 'code' => 'ZULIA', 'name' => 'Zulia'],
            ['country_id' => $countries['VE'], 'code' => 'DISTRITO_CAPITAL', 'name' => 'Distrito Capital'],

            // 🇵🇪 PERÚ
            ['country_id' => $countries['PE'], 'code' => 'AMAZONAS', 'name' => 'Amazonas'],
            ['country_id' => $countries['PE'], 'code' => 'ANCASH', 'name' => 'Áncash'],
            ['country_id' => $countries['PE'], 'code' => 'APURIMAC', 'name' => 'Apurímac'],
            ['country_id' => $countries['PE'], 'code' => 'AREQUIPA', 'name' => 'Arequipa'],
            ['country_id' => $countries['PE'], 'code' => 'AYACUCHO', 'name' => 'Ayacucho'],
            ['country_id' => $countries['PE'], 'code' => 'CAJAMARCA', 'name' => 'Cajamarca'],
            ['country_id' => $countries['PE'], 'code' => 'CALLAO', 'name' => 'Callao'],
            ['country_id' => $countries['PE'], 'code' => 'CUSCO', 'name' => 'Cusco'],
            ['country_id' => $countries['PE'], 'code' => 'HUANCAVELICA', 'name' => 'Huancavelica'],
            ['country_id' => $countries['PE'], 'code' => 'HUANUCO', 'name' => 'Huánuco'],
            ['country_id' => $countries['PE'], 'code' => 'ICA', 'name' => 'Ica'],
            ['country_id' => $countries['PE'], 'code' => 'JUNIN', 'name' => 'Junín'],
            ['country_id' => $countries['PE'], 'code' => 'LA_LIBERTAD', 'name' => 'La Libertad'],
            ['country_id' => $countries['PE'], 'code' => 'LAMBAYEQUE', 'name' => 'Lambayeque'],
            ['country_id' => $countries['PE'], 'code' => 'LIMA', 'name' => 'Lima'],
            ['country_id' => $countries['PE'], 'code' => 'LORETO', 'name' => 'Loreto'],
            ['country_id' => $countries['PE'], 'code' => 'MADRE_DE_DIOS', 'name' => 'Madre de Dios'],
            ['country_id' => $countries['PE'], 'code' => 'MOQUEGUA', 'name' => 'Moquegua'],
            ['country_id' => $countries['PE'], 'code' => 'PASCO', 'name' => 'Pasco'],
            ['country_id' => $countries['PE'], 'code' => 'PIURA', 'name' => 'Piura'],
            ['country_id' => $countries['PE'], 'code' => 'PUNO', 'name' => 'Puno'],
            ['country_id' => $countries['PE'], 'code' => 'SAN_MARTIN', 'name' => 'San Martín'],
            ['country_id' => $countries['PE'], 'code' => 'TACNA', 'name' => 'Tacna'],
            ['country_id' => $countries['PE'], 'code' => 'TUMBES', 'name' => 'Tumbes'],
            ['country_id' => $countries['PE'], 'code' => 'UCAYALI', 'name' => 'Ucayali'],

            // 🇦🇷 ARGENTINA
            ['country_id' => $countries['AR'], 'code' => 'BUENOS_AIRES', 'name' => 'Buenos Aires'],
            ['country_id' => $countries['AR'], 'code' => 'CABA', 'name' => 'Ciudad Autónoma de Buenos Aires'],
            ['country_id' => $countries['AR'], 'code' => 'CATAMARCA', 'name' => 'Catamarca'],
            ['country_id' => $countries['AR'], 'code' => 'CHACO', 'name' => 'Chaco'],
            ['country_id' => $countries['AR'], 'code' => 'CHUBUT', 'name' => 'Chubut'],
            ['country_id' => $countries['AR'], 'code' => 'CORDOBA', 'name' => 'Córdoba'],
            ['country_id' => $countries['AR'], 'code' => 'CORRIENTES', 'name' => 'Corrientes'],
            ['country_id' => $countries['AR'], 'code' => 'ENTRE_RIOS', 'name' => 'Entre Ríos'],
            ['country_id' => $countries['AR'], 'code' => 'FORMOSA', 'name' => 'Formosa'],
            ['country_id' => $countries['AR'], 'code' => 'JUJUY', 'name' => 'Jujuy'],
            ['country_id' => $countries['AR'], 'code' => 'LA_PAMPA', 'name' => 'La Pampa'],
            ['country_id' => $countries['AR'], 'code' => 'LA_RIOJA', 'name' => 'La Rioja'],
            ['country_id' => $countries['AR'], 'code' => 'MENDOZA', 'name' => 'Mendoza'],
            ['country_id' => $countries['AR'], 'code' => 'MISIONES', 'name' => 'Misiones'],
            ['country_id' => $countries['AR'], 'code' => 'NEUQUEN', 'name' => 'Neuquén'],
            ['country_id' => $countries['AR'], 'code' => 'RIO_NEGRO', 'name' => 'Río Negro'],
            ['country_id' => $countries['AR'], 'code' => 'SALTA', 'name' => 'Salta'],
            ['country_id' => $countries['AR'], 'code' => 'SAN_JUAN', 'name' => 'San Juan'],
            ['country_id' => $countries['AR'], 'code' => 'SAN_LUIS', 'name' => 'San Luis'],
            ['country_id' => $countries['AR'], 'code' => 'SANTA_CRUZ', 'name' => 'Santa Cruz'],
            ['country_id' => $countries['AR'], 'code' => 'SANTA_FE', 'name' => 'Santa Fe'],
            ['country_id' => $countries['AR'], 'code' => 'SANTIAGO_DEL_ESTERO', 'name' => 'Santiago del Estero'],
            ['country_id' => $countries['AR'], 'code' => 'TIERRA_DEL_FUEGO', 'name' => 'Tierra del Fuego'],
            ['country_id' => $countries['AR'], 'code' => 'TUCUMAN', 'name' => 'Tucumán'],

            // 🇨🇱 CHILE
            ['country_id' => $countries['CL'], 'code' => 'ARICA_PARINACOTA', 'name' => 'Arica y Parinacota'],
            ['country_id' => $countries['CL'], 'code' => 'TARAPACA', 'name' => 'Tarapacá'],
            ['country_id' => $countries['CL'], 'code' => 'ANTOFAGASTA', 'name' => 'Antofagasta'],
            ['country_id' => $countries['CL'], 'code' => 'ATACAMA', 'name' => 'Atacama'],
            ['country_id' => $countries['CL'], 'code' => 'COQUIMBO', 'name' => 'Coquimbo'],
            ['country_id' => $countries['CL'], 'code' => 'VALPARAISO', 'name' => 'Valparaíso'],
            ['country_id' => $countries['CL'], 'code' => 'METROPOLITANA', 'name' => 'Región Metropolitana'],
            ['country_id' => $countries['CL'], 'code' => 'OHIGGINS', 'name' => "O'Higgins"],
            ['country_id' => $countries['CL'], 'code' => 'MAULE', 'name' => 'Maule'],
            ['country_id' => $countries['CL'], 'code' => 'NUBLE', 'name' => 'Ñuble'],
            ['country_id' => $countries['CL'], 'code' => 'BIOBIO', 'name' => 'Biobío'],
            ['country_id' => $countries['CL'], 'code' => 'ARAUCANIA', 'name' => 'La Araucanía'],
            ['country_id' => $countries['CL'], 'code' => 'LOS_RIOS', 'name' => 'Los Ríos'],
            ['country_id' => $countries['CL'], 'code' => 'LOS_LAGOS', 'name' => 'Los Lagos'],
            ['country_id' => $countries['CL'], 'code' => 'AYSEN', 'name' => 'Aysén'],
            ['country_id' => $countries['CL'], 'code' => 'MAGALLANES', 'name' => 'Magallanes y Antártica Chilena'],

            // 🇧🇴 BOLIVIA
            ['country_id' => $countries['BO'], 'code' => 'BENI', 'name' => 'Beni'],
            ['country_id' => $countries['BO'], 'code' => 'CHUQUISACA', 'name' => 'Chuquisaca'],
            ['country_id' => $countries['BO'], 'code' => 'COCHABAMBA', 'name' => 'Cochabamba'],
            ['country_id' => $countries['BO'], 'code' => 'LA_PAZ', 'name' => 'La Paz'],
            ['country_id' => $countries['BO'], 'code' => 'ORURO', 'name' => 'Oruro'],
            ['country_id' => $countries['BO'], 'code' => 'PANDO', 'name' => 'Pando'],
            ['country_id' => $countries['BO'], 'code' => 'POTOSI', 'name' => 'Potosí'],
            ['country_id' => $countries['BO'], 'code' => 'SANTA_CRUZ', 'name' => 'Santa Cruz'],
            ['country_id' => $countries['BO'], 'code' => 'TARIJA', 'name' => 'Tarija'],

            // 🇵🇦 PANAMÁ
            ['country_id' => $countries['PA'], 'code' => 'BOCAS_DEL_TORO', 'name' => 'Bocas del Toro'],
            ['country_id' => $countries['PA'], 'code' => 'CHIRIQUI', 'name' => 'Chiriquí'],
            ['country_id' => $countries['PA'], 'code' => 'COCLE', 'name' => 'Coclé'],
            ['country_id' => $countries['PA'], 'code' => 'COLON', 'name' => 'Colón'],
            ['country_id' => $countries['PA'], 'code' => 'DARIEN', 'name' => 'Darién'],
            ['country_id' => $countries['PA'], 'code' => 'HERRERA', 'name' => 'Herrera'],
            ['country_id' => $countries['PA'], 'code' => 'LOS_SANTOS', 'name' => 'Los Santos'],
            ['country_id' => $countries['PA'], 'code' => 'PANAMA', 'name' => 'Panamá'],
            ['country_id' => $countries['PA'], 'code' => 'PANAMA_OESTE', 'name' => 'Panamá Oeste'],
            ['country_id' => $countries['PA'], 'code' => 'VERAGUAS', 'name' => 'Veraguas'],
            ['country_id' => $countries['PA'], 'code' => 'GUNA_YALA', 'name' => 'Guna Yala'],
            ['country_id' => $countries['PA'], 'code' => 'NGABE_BUGLE', 'name' => 'Ngäbe-Buglé'],
            ['country_id' => $countries['PA'], 'code' => 'EMBERA_WOUNAAN', 'name' => 'Emberá-Wounaan'],
            ['country_id' => $countries['PA'], 'code' => 'GUNA_DE_MADUGANDI', 'name' => 'Guna de Madugandí'],
            ['country_id' => $countries['PA'], 'code' => 'GUNA_DE_WARGANDI', 'name' => 'Guna de Wargandí'],
        ];

        DB::table('states')->upsert(
            $states,
            ['country_id', 'name'],
            ['code']
        );
    }
}
